### ISSUE TITLE
FileToImageToFile.cpp 中节区从 FileBuffer 写入 ImageBuffer 的长度问题

### ISSUE THREAD

**Issue by luedong776** [Kazamayc/PEtools#1]
61 行，SizeOfRawData 参数应该是和节表 Misc 字段取一个最大值，然后对齐内存 SectionAlignment？
```
memcpy(ImageBuffer+VirtualAddress,FileBuffer+PointerToRawData,SizeOfRawData);
```

**Comment by Kazamayc** [comment]
直接用SizeOfRawData，misc存储的是内存中未初始化变量拉伸以后的长度，没初始化的全局变量存储在内存的bss段，不被文件所保存，文件应该是只会在节表中记录一下，不给它分配节，然后虚拟内存自己给他分配。
你从内存中直接复制回文件，文件也不会存那些拉伸以后的全局变量。所以用misc是不正确的。

**Comment by Kazamayc** [comment]
或者你可以这样想，你从文件复制到内存什么东西，就应该从内存中把那些东西取回来，而不是取回来拉伸以后的值
